config = {'train_data_path':['/home/cougarnet.uh.edu/mpadmana/Desktop/raw_files/subset0/'],
          'val_data_path':['/home/cougarnet.uh.edu/mpadmana/Desktop/raw_files/subset1/'], 
          'test_data_path':['/home/cougarnet.uh.edu/mpadmana/Desktop/raw_files/subset2/'], 
          
          'train_preprocess_result_path':'/home/mpadmana/anaconda3/envs/DeepLung_original/methodist_train_files/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/home/mpadmana/anaconda3/envs/DeepLung_original/methodist_val_files/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/home/mpadmana/anaconda3/envs/DeepLung_original/methodist_val_files/',
          
          'train_annos_path':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/evaluationScript/annotations/annotations.csv',
          'val_annos_path':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/evaluationScript/annotations/annotations.csv',
          'test_annos_path':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/evaluationScript/annotations/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'/home/cougarnet.uh.edu/mpadmana/Downloads/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/prepared/',
          'luna_data':'/home/cougarnet.uh.edu/mpadmana/Desktop/raw_files/',
          'luna_label':'/home/cougarnet.uh.edu/mpadmana/DeepLung_original/evaluationScript/annotations/annotations.csv'
         } 
